manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson/
  projects:
    - name: zmk
      remote: petejohnson
      revision: feat/pointers-move-scroll
      import: app/west.yml
  self:
    path: config
